version: '3'

services:
  clavardage:
    image: java:8-jre
    networks:
      - clavardnet
    volumes:
      - ./target/classes/:/app
    command: java -Dfile.encoding=UTF-8 -classpath /app org.etudinsa.clavardage.ui.CLI

networks:
  clavardnet:
    internal: true

